### ISSUE TITLE
Not finding my PWS

### ISSUE THREAD

**Issue by wags1** [cytech/weather.multi#1]
This looks promising but for some reason it is currently not pulling up my PWS - KPAKUTZT4. I put in wupws:kutztown, I select Kutztown PA from the list, and it pulls a list of weather stations in the area but mine is not in the list. My PWS is working and reporting into WU correctly and I have a working WU API key.
I noticed that you are only pulling 10 PWSs for any city I enter. Perhaps that is the issue?

**Comment by cytech** [comment]
yeah,  the WU search looks at the nearest city on the map to find the station, even though the station id is listed in a different city.

In your case search New Smithville, and your station shows up.
wupws:new smithville

New Smithville, Pennsylvania, United States

KPAKUTZT4
0.76 miles from selected city

**Comment by wags1** [comment]
Thanks. You may want to note that in the settings or in the read.me. I'm guessing it will trip up other folks as well as "New Smithville" isn't associated with my PWS anywhere on WU that I could find. How did you even find that out? I live here and would never have even thought to search for "New Smithville"...it's not really a town...LOL.

**Comment by cytech** [comment]
i have the same issue. my mailing address city (which is the one registered with Wu on the station) is physically 20 miles from the actual city on the map. the search is looking for the station lat/lon closest to the city.

the other option for these situations is to configure any nearby station. Then edit ~/.kodi/userdata/addon_data/weather.multi/settings.xml and modify
the setting id "locX", "locXid", "locaXlat", and "locXlon" for that temporary station to your own station information.
then restart kodi and it should be working.

to answer your question, i searched on WeatherUnderground for you station ID. when it showed on the map, New Smithville was the closest city to your physical location.

**Comment by wags1** [comment]
I wonder if there is some other way to do the search so that it uses the city associated with the PWS. I’m just anticipating that lots of folks will have the same issue that we do. It will just generate questions/problems from people trying to use it. 
I really do have to LOL though at “New Smithville”...it is literally not a town at all but an intersection. One of those weird “map points”.

**Comment by mfreeman72** [comment]
I'm having the same issue, but I'm in the city I'm registered in. But again, it only shows 10 of the weather stations, and there are tons more, including mine, which are not showing on the list. Is there a way to just enter the weather station ID directly into the search? For example, my weather station ID is KCAFRESN189. Could it be made to directly connect to that by entering wupws:KCAFRESN189 instead of the city name?

**Comment by mfreeman72** [comment]
I also have an Ambient Weather account (that's the maker of my PWS), but even though it can find my station, it's giving an error, and the temperature reads 32 degrees F.

**Comment by cytech** [comment]
the other option for these situations is to configure any nearby station. Then edit ~/.kodi/userdata/addon_data/weather.multi/settings.xml and modify
the setting id "locX", "locXid", "locaXlat", and "locXlon" for that temporary station to your own station information.
then restart kodi and it should be working.

**Comment by mfreeman72** [comment]
Yes, that worked. Thank you!
