### ISSUE TITLE
general problem with weather.multi

### ISSUE THREAD

**Issue by 32Dexter** [cytech/weather.multi#2]
Hi, this addon works quite well, but not totally:
- The real time does NOT work (icon visible from the main home page)
- Daily forecast works
- Hourly forecasts NOT work
- The maps work
Could you help me?

**Comment by cytech** [comment]
this is a fork of Fork of the weather.multi addon for Kodi 19 by ronie https://gitlab.com/ronie/weather.multi
its purpose is only to add weatherunderground PWS and ambient weather.
dailies are based on the  provider set.
hourly only works for the yahoo or Extended weather providers. ambient and WU do not provide this data.
Ambient does not provide any forecast data so the daiies are based on yahoo.
I dont know about the realtime issue.
