### ISSUE TITLE
Broken menu entries in 19.5

### ISSUE THREAD

**Issue by Megachip** [cytech/weather.multi#4]
![BB957F00-387B-44A6-BCE0-C48F2099F724](https://user-images.githubusercontent.com/487352/216812898-eadc1b94-9d3b-4783-9a5b-090b43563ebc.jpeg)
Happens on English and German, other languages not tested

**Comment by cytech** [comment]
v1.0.18    fixed en_gb/strings.po translation
Note: Only the en_gb translation file is correct for this addon. All other translations will show missing information in the addon configuration.  
Feel free to update the other translations using en_gb as the base...
